export const namespace = {
  GEOJSON_HEATMAP_GET: 'GEOJSON_HEATMAP_GET',
  GEOJSON_HEATMAP_GET_SUCCESS: 'GEOJSON_HEATMAP_GET_SUCCESS',
  GEOJSON_INTERESTS_GET: 'GEOJSON_INTERESTS_GET',
  GEOJSON_INTERESTS_GET_SUCCESS: 'GEOJSON_INTERESTS_GET_SUCCESS',
  
  CHUCK_GET: 'CHUCK_GET',
  CHUCK_GET_SUCCESS: 'CHUCK_GET_SUCCESS'
};
