export const namespace = {
  GEOJSON_BOUNDS_GET: 'GEOJSON_BOUNDS_GET',
  GEOJSON_BOUNDS_GET_SUCCESS: 'GEOJSON_BOUNDS_GET_SUCCESS',
  GEOJSON_HEATMAP_GET: 'GEOJSON_HEATMAP_GET',
  GEOJSON_HEATMAP_GET_SUCCESS: 'GEOJSON_HEATMAP_GET_SUCCESS',
  GEOJSON_INTERESTS_GET: 'GEOJSON_INTERESTS_GET',
  GEOJSON_INTERESTS_GET_SUCCESS: 'GEOJSON_INTERESTS_GET_SUCCESS'
};
