export const namespace = {
  GEOJSON_BOUNDS_GET: 'GEOJSON_BOUNDS_GET',
  GEOJSON_BOUNDS_GET_SUCCESS: 'GEOJSON_BOUNDS_GET_SUCCESS',
  GEOJSON_HEATMAP_GET: 'GEOJSON_HEATMAP_GET',
  GEOJSON_HEATMAP_GET_SUCCESS: 'GEOJSON_HEATMAP_GET_SUCCESS',
  GEOJSON_INTERESTS_GET: 'GEOJSON_INTERESTS_GET',
  GEOJSON_INTERESTS_GET_SUCCESS: 'GEOJSON_INTERESTS_GET_SUCCESS',

  SET_ACTIVE_OPTION: 'SET_ACTIVE_OPTION',

  ROUTES_GET: 'ROUTES_GET',
  ROUTES_GET_SUCCESS: 'ROUTES_GET_SUCCESS',
  ROUTES_DEL: 'ROUTES_DEL'
};
